version: '3.9'

services:
  cloodcbr:
    container_name: cloodcbr
    build: './api'
    image: cloodcbr/app:latest
    working_dir: /app
    networks:
      - cloodcbr-net
    volumes:
      - ./api:/app
      - clood-nodemodules:/app/node_modules
    ports: ['3000:3000', '3002:3002']

  clood-dashboard:
    container_name: cloodcbr-dashboard
    build: './dashboard'
    image: cloodcbr/dashboard:latest
    working_dir: /dashboard
    networks:
      - cloodcbr-net
    volumes:
      - ./dashboard/app:/dashboard/app
    ports:
      - 8000:8000

  cloodcbr-other-use:
    container_name: cloodcbr-other-use
    build: './other-services/use-vector'
    image: cloodcbr/other-use:latest
    working_dir: /app
    networks:
      - cloodcbr-net
    ports:
      - 4100:4100

  cloodcbr-other-ontology-sim:
    container_name: cloodcbr-other-ontology-sim
    build: './other-services/ontology-sim'
    image: cloodcbr/other-ontology-sim:latest
    working_dir: /app
    networks:
      - cloodcbr-net
    ports:
      - 4200:3000
    volumes:
      - ./other-services/ontology-sim:/app
      - clood-ontology-nodemodules:/app/node_modules

  cloodcbr-other-semantic-sim:
    container_name: cloodcbr-other-semantic-sim
    build: './other-services/semantic-sim'
    image: cloodcbr/other-semantic-sim:latest
    working_dir: /app
    networks:
      - cloodcbr-net
    ports:
      - 4300:80
    volumes:
      - ./other-services/semantic-sim:/app
    restart: on-failure

  clood-opensearch:
    image: opensearchproject/opensearch:1.3.1
    container_name: clood-opensearch
    environment:
      - cluster.name=opensearch-cluster
      - node.name=clood-opensearch
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - "DISABLE_INSTALL_DEMO_CONFIG=true" # disables execution of install_demo_configuration.sh bundled with security plugin, which installs demo certificates and security configurations to OpenSearch
      - "DISABLE_SECURITY_PLUGIN=true" # disables security plugin entirely in OpenSearch by setting plugins.security.disabled: true in opensearch.yml
      - "discovery.type=single-node" # disables bootstrap checks that are enabled when network.host is set to a non-loopback address
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - clood-opensearch-data:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - cloodcbr-net

  clood-opensearch-dashboard:
    image: opensearchproject/opensearch-dashboards:1.3.0
    container_name: clood-opensearch-dashboard
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      - 'OPENSEARCH_HOSTS=["http://clood-opensearch:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true" # disables security dashboards plugin in OpenSearch Dashboards
    networks:
      - cloodcbr-net

volumes:
  clood-opensearch-data: {}
  clood-nodemodules: {}
  clood-ontology-nodemodules: {}

networks:
  cloodcbr-net:
    driver: bridge
